### ISSUE TITLE
Update git submodule

### ISSUE THREAD

**Issue by luwol03** [ankicommunity/anki-devops-services#13]
Hello guys,

I found it very difficult to understand, how these repos are connected together. so I then made myself and made a simple diagram.  in doing so, i came across the question, why don't you take your own anki sync server out of the organization.  that made it very difficult for me to understand.

I suggest to update the git submodule to the organizations anki sync server.

![Anki-Seite-2](https://user-images.githubusercontent.com/60048565/99197485-1ae7b280-2793-11eb-90bc-70203f8036c3.png)

**Comment by kuklinistvan** [comment]
Hello @luwol03,

For the record, I'm quoting you and @VikashKothary from Gitter:

> can anyone explain to me why the structure of each server project is so complicated? i once set up a small diagram and wanted to ask two questions about it.
> is what I have drawn so correct?
> why does ankicommunity/docker-anki-sync-server not use ankicommunity/anki-sync-server but kuklinistvan/anki-sync-server ?

> Hi @luwol03, that's a very good question. Here are my comments:
>
> The first thing to note about why there are so many different versions of the applications. The main reason is that before this community, each project was maintained by separate individuals. As such, each individual project had different forks and different features. See this ticket for a brief history of where the projects came from: https://github.com/ankicommunity/anki-sync-server/issues/33#issuecomment-711421178
>
> The second thing to note is that we're in the process of aligning and combining all these repos into a single stable collaborative project. You will see multiple issues regarding this across all the repos.
>
> Now what does this mean for you. To provide any recommendations we'd need to understand your requirements however you mentioned production use so I'll riff on that a little.
>
> Production usage has a lot more steps then picking between the two sync servers e.g. a scalable database architecture, load balancing, etc. But I'm assume what you are asking for is which is more stable for long term usage. I support @kuklinistvan's recommendations to use the anki-sync-server. This is simply because that is the project which has the more current users. I would even take it a step future that you open a ticket in the docker-anki-sync-server to update the docker image source to the anticommunity repo. It would add some considerable changes include bug fixes and new features.
>
> That being said, your interest in migrating to the Django version is very valid. Again @kuklinistvan's recommendations are the best advice at this time. That being said, I want it to be clear that there will be a clear migration path for all those who want to adopt the newer project once it becomes the default.

**Comment by VikashKothary** [comment]
This project no longer uses git submodules. It will download the latest release at the time of building.

I hope this resolves this issue. Feel free to open it again if there's anything I missed.
