### ISSUE TITLE
Move to a Standalone Repo

### ISSUE THREAD

**Issue by VikashKothary** [ankicommunity/anki-devops-services#17]
Forks are treaded as second class citizens on Github. There was also a discussion on the `anki-sync-server` about how it causes confusion: https://github.com/ankicommunity/anki-sync-server/issues/2.

You can see how here: https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project. It involves contacting support. When I did it for the above, I just send them the ticket, and asked them to do it. 

I just wanted to run it by you. Let me know what you think?

**Comment by VikashKothary** [comment]
I'm going to pick this up :)

**Comment by kuklinistvan** [comment]
Thank you!

**Comment by VikashKothary** [comment]
This has now been resolved.
