### ISSUE TITLE
Remove `portaudio-dev` dependency 

### ISSUE THREAD

**Issue by chewblacka** [ankicommunity/anki-devops-services#23]
Hi,
I was just wondering why the anki-sync-server docker build requires audio / pyaudio? I realize that anki is capable of audio support (a feature I actually use in some of my decks). But I still don't understand why the sync-server needs audio support? Have I misunderstood a function of the sync server? I use it to synchronize anki decks between different instances of anki I have running (e.g. on different computers). Why does the server need or how does it utilize audio? Many thanks!

**Comment by VikashKothary** [comment]
Hi @chewblacka,

You've asked a very good question. 

Historically, this server used to use the `anki` source code as a submodule. The `anki` dependency required `PyAudio` to be present when building the project. 

But my understanding is that when we updated to use the `anki` dependency on PyPI, this meant that `PyAudio` is not longer required. See old documetation: https://github.com/ankicommunity/anki-sync-server/commit/7deda95d77b488b26242b64aafa5ebd709fa1e24.

As such, this ticket should be named to `Remove portaudio-dev` and it will be dependent on a new ticket to remove pyaudio from the anki-sync-server.
