### ISSUE TITLE
Update folder structure

### ISSUE THREAD

**Issue by VikashKothary** [ankicommunity/anki-devops-services#27]
# Current

```
- Docker
	- djankiserv
	- legacy_tsudoko
- Docker Componse
	- djankiserv
```

# Recommended

```
- djankiserv
	  - images (docker)
	  - examples (docker compose)
	  - manifests (kubernates)
	  - charts (helm)
- anki-sync-server (legacy_tsudoko)
	  - images
	  - ...
```

# Why

Because the images aren't related, it's better to store them separately. The benefit of this, is that you minimise the shared code so you can make changes to one image without making changes to another. 

What do you think @kuklinistvan ?

**Comment by kuklinistvan** [comment]
I love the idea, let's do this :)
