### ISSUE TITLE
Use Environment Variables

### ISSUE THREAD

**Issue by VikashKothary** [ankicommunity/anki-devops-services#3]
We should remove https://github.com/ankicommunity/docker-anki-sync-server/blob/master/Docker/config/ankisyncd.conf.example and use environment variables (https://github.com/ankicommunity/anki-sync-server#envvar-configuration-overrides) instead. 

This will simplify the build and more familiar to Docker users. This will be the preferred method of configuration in the future. Thoughts?

**Comment by VikashKothary** [comment]
I agree with what you're saying. We shouldn't make a breaking change. By default, environment variables will work and override the config anyway. But for the future, imo we should advice the use of environment variables, as future versions of the sync server may remove the configuration file.

We can close this issue for now.

**Comment by kuklinistvan** [comment]
Out of interest, why do we wish to deprecate the configuration file? I mean, we have plenty of them under `/etc`, as most of our servers read their settings from there.

**Comment by kuklinistvan** [comment]
> We can close this issue for now.

Do we support environment variables already? :)

**Comment by VikashKothary** [comment]
I've not tested it. But the anki sync server currently supports environment variables. As linked above. 
We could add documentation around it, but it isn't critical right now.

**Comment by kuklinistvan** [comment]
Okay, closing this then and we'll get back to here once it becomes a priority.

**Comment by VikashKothary** [comment]
I think this has come back in the implementation of your new `Configuration` folder. You're using `.vars` files in the case I believe we should use `.env` files. Docker Compose automatically loads them, its the default for bash/shell and using them in Python is exteremely easy using `python-dotenv`.

Let me know what you think.
